version: '3'

services:
  irods-catalog-provider:
    build:
        context: irods
        dockerfile: Dockerfile.provider
    hostname: icat.example.org
    networks:
      default:
        aliases:
          - icat.example.org
  irods-automated-ingest:
    build:
        context: ingest
        dockerfile: Dockerfile.ingest
    hostname: irods-ingest.example.org
    networks:
      default:
        aliases:
          - irods-ingest.example.org
    depends_on:
      - irods-catalog-provider
