version: '3'

services:
  irods-catalog-provider:
    build:
        context: irods
        dockerfile: Dockerfile.provider
    hostname: icat.example.org
    networks:
      default:
        aliases:
          - icat.example.org
  irods-automated-ingest:
    build:
        context: ingest
        dockerfile: Dockerfile.ingest
    hostname: irods-ingest.example.org
    networks:
      default:
        aliases:
          - irods-ingest.example.org
    depends_on:
      - irods-catalog-provider
  irods-audit-elk-stack:
    image: irods/irods_audit_elk_stack:latest
    hostname: irods-audit-elastic-stack.example.org
    ports:
      - "8080:15672"
      - "5672:5672"
      - "80:5601"
      - "9200:9200"
    networks:
      default:
        aliases:
          - irods-audit-elastic-stack.example.org
    volumes:
      - "./audit/entrypoint.sh:/audit/entrypoint.sh:ro"
    entrypoint: /audit/entrypoint.sh
